name: Build BAR files

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        regitry: cp.icr.io
        username: cp
        password: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE2NzQ1NzY2MDQsImp0aSI6IjE1NjIxMjg2M2M4NjQ1NmE5ZGExNWM4ZDNhYzM3YjRjIn0.Y1FjMqwaMyNIwN-LvDODWi-l2eHkmfUqpPqJWqSn0ZQ
          
    - name: Download ACE image
      run: |
        curl -so moby-download-frozen-image-v2.sh https://raw.githubusercontent.com/moby/moby/master/contrib/download-frozen-image-v2.sh
        mkdir ace-minimal-download
        bash moby-download-frozen-image-v2.sh ace-minimal-download tdolby/experimental:ace-minimal-12.0.4.0-alpine
        mkdir ace-minimal-image-unzip
        cd ace-minimal-download && grep layer.tar manifest.json | tr -d '"' | tr -d ',' | xargs -n 1 tar -C ../ace-minimal-image-unzip -xf && cd - && rm -rf ace-minimal-download
        sed -i 's/\/bin\/mksh/\/bin\/bash/g' ace-minimal-image-unzip/opt/ibm/ace-12/ace ace-minimal-image-unzip/opt/ibm/ace-12/server/bin/mqsicreateworkdir ace-minimal-image-unzip/opt/ibm/ace-12/server/bin/mqsipackagebar
    - name: Set up ACE environment
      run: |
        export LICENSE=accept
        export MQSI_WORKPATH=$GITHUB_WORKSPACE/ace-minimal-image-unzip/var/mqsi
        . ace-minimal-image-unzip/opt/ibm/ace-12/server/bin/mqsiprofile
    - name: Check command exists
      run: command -v mqsipackagebar || echo "Command not found"
    - name: Build BAR files
      run: |
        mqsipackagebar -data $GITHUB_WORKSPACE/ace-projects -b $GITHUB_WORKSPACE/bar-files -a
